name: Run bot and push updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # daily at noon UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run bot script
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: node dist/bot.js

      - name: Commit and push updates
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add posted_links.txt recent_keywords.txt
          git diff --cached --quiet || git commit -m "Update posted links and recent keywords [skip ci]"

          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin HEAD:${GITHUB_REF_NAME}
