name: Run Bluesky Positive News Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
      BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Important for custom git push auth

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Debug remote URL
        run: |
          echo "https://x-access-token:${PAT_TOKEN}@github.com/HayJayB/hopecorenewTS.git"

      - name: Configure Git to use PAT for pushing
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/HayJayB/hopecorenewTS.git

      - name: Run bot
        run: node dist/bot.js

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posted_links.txt recent_keywords.txt || echo "No changes to add"
          git commit -m "Update posted links and recent keywords [skip ci]" || echo "No changes to commit"
          git push origin main
