name: Post Bluesky News

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean previous build
        run: rm -rf dist node_modules

      - name: Install dependencies
        run: |
          npm install
          npm install node-fetch@2 @types/node-fetch@2 --save-dev

      - name: Verify installed @atproto/api version
        run: npm list @atproto/api

      - name: Build TypeScript
        run: npm run build

      - name: Debug working directory and files
        run: |
          echo "Working directory:"
          pwd
          echo "Files in root:"
          ls -la
          echo "Checking posted_links.txt and recent_keywords.txt presence:"
          ls -la posted_links.txt recent_keywords.txt || echo "Files not found"

      - name: Run bot
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
        run: node dist/bot.js
