name: Post Bluesky News

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean previous build
        run: rm -rf dist node_modules

      - name: Install dependencies
        run: |
          npm install
          npm install node-fetch@2 @types/node-fetch@2 --save-dev

      - name: Verify installed @atproto/api version
        run: npm list @atproto/api

      - name: Build TypeScript
        run: npm run build

      - name: Run bot
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
        run: node dist/bot.js

      - name: Configure Git for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit updated files if any
        run: |
          git add posted_links.txt recent_keywords.txt
          if ! git diff --cached --quiet; then
            git commit -m "Update posted links and recent keywords [skip ci]"
            git push origin HEAD:${{ github.ref }}
          else
            echo "No changes to commit"
          fi
