name: Run Bluesky Positive News Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean workspace
        run: rm -rf dist node_modules

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run bot script
        run: node dist/bot.js
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}

      - name: Configure Git for Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit updated txt files
        run: |
          git add posted_links.txt recent_keywords.txt
          if ! git diff --cached --quiet; then
            git commit -m "Update posted links and recent keywords [skip ci]"
            git push origin HEAD:${{ github.ref }}
          else
            echo "No changes to commit"
          fi
