name: Run Bluesky Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  # <-- Important: disable auto credentials

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run bot
        run: node dist/bot.js

      - name: Debug remote URL
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Remote URL for push:"
          echo "https://x-access-token:${PAT_TOKEN}@github.com/HayJayB/hopecorenewTS.git"

      - name: Configure git for pushing changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin "https://x-access-token:${PAT_TOKEN}@github.com/HayJayB/hopecorenewTS.git"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add posted_links.txt recent_keywords.txt
          git commit -m "Update posted links and recent keywords [skip ci]" || echo "No changes to commit"
          git push origin main
